name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Add schedule for smoke tests
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.8.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm test:e2e:ci
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: webapp/test/e2e/playwright-report/
          retention-days: 30
          
  smoke-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    environment: production
    defaults:
      run:
        working-directory: webapp
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.8.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Smoke Tests
        run: pnpm test:e2e:smoke
        env:
          SMOKE_TEST_URL: ${{ secrets.PRODUCTION_URL }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-smoke-report
          path: webapp/test/e2e/playwright-report/
          retention-days: 30 